version: '3'
services:
  server:
    build:
      context: ./
    container_name: zefrancisco-carrier-cost-api-app
    entrypoint: dockerize -wait tcp://dbps:5432 -timeout 40s ./.docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    ports:
      - "3333:3333"
    depends_on: 
      - dbps

  dbps:
    build: .docker/postgres
    container_name: zefrancisco-carrier-cost-api-dbps
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=case_back_end_db
    ports:
     - "5432:5432"
    volumes:
    #  - ./mysql/CreateDatabase.sql:/docker-entrypoint-initdb.d/0_init.sql
      - .docker/dbdata-mysql:/var/lib/postgresql/data